export default [
  'Le privilège des blancs.',
  'Un anus maquillé.',
  'Les filles qui envoient tout le temps des Snaps.',
  'Le FN.',
  'La crucifixion',
  'Une épilation au laser qui a mal tournée.',
  'Une petite caresse sur la cuisse.',
  'Une sodomie polissonne.',
  'Tirer un coup de fusil tout en enculant un sanglier qui couine.',
  'Des mouvements de Nunchakus.',
  'Des orphelins réconfortants.',
  'Une haleine de pénis.',
  'Manger un albinos.',
  'Des chatouilles sur les couilles.',
  'Les dents qui claquent.',
  'Laisser tomber tout le monde.',
  'IL FAUT CONSTRUIRE DES AUTOROUTES.',
  "Faire sauter l'Assemblée Nationale.",
]
